version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_app
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./src/db:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
  server:
    image: ebobrow/chat-app-server
    depends_on:
      - db
    ports:
      - '4000:4000'
    env_file:
      - docker.env
    restart: unless-stopped
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - server
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email elliotgreybobrow@gmail.com --agree-tos --no-eff-email --staging -d api.whazzapp.elliotbobrow.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/elliot/chatapp-server
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/elliot/chatapp-server/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
